Issue/tde#5 #29 papa johns
dokidzung/32BitJam pull request #34
Opened 2021-09-14 00:36 UTC by charlesamacon

Added that fancy dash effect to the player (press space when moving)
Added better camera
Added bkg texture

Closes #5 
Closes #29

2021-09-14 01:23 UTC, dokidzung commented
pizza time

2021-09-14 23:59 UTC, JustAnotherNerdWhoLikesStuff commented on Assets/Scripts/Utility/SetBottomMeshToZero.cs
> +        transform.position = new Vector3(transform.position.x, transform.localScale.y, transform.position.z / 2.0f);
I already found more problems with this script that should be addressed later.  Mostly that the one parameter with scale is in the `y` instead of `z` dimension, and that the wrong scale variable is used (should be `lossyScale`, which is relative to the world.
Again, things that we'll fix later.

2021-09-15 00:01 UTC, JustAnotherNerdWhoLikesStuff approved these changes
The filename `Assets/Prefabs/Utility/Dash Particle.prefab` makes me a bit sad because it has a space, but that's probably the batch-scripting related PTSD kicking in.

2021-09-15 00:10 UTC, JustAnotherNerdWhoLikesStuff requested changes
Ignore approval; just realized this should be on top of develop-top-down and not develop.  That will also mean it needs to rebase on the most recent changes.

2021-09-15 18:56 UTC, JustAnotherNerdWhoLikesStuff approved these changes
Alright, it's good now.

2021-09-15 19:23 UTC, merged